### ISSUE TITLE
Alpha Checklist

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#168]
- [x] Camera crash
- [x] Change ios plugin class names to avoid clashes
- [x] Storage on Android
- [x] Test Android gradle sync required
- [x] Storage JSON
- [x] Common Cordova pod 
- [x] Create command
- [x] Clean up experience when `www` or web folder isn't found:
- [x] android-template in gradle

<img width="1219" alt="screen shot 2018-02-24 at 11 42 52 am" src="https://user-images.githubusercontent.com/11214/36633278-20e46fb2-1958-11e8-991c-0642ad9b2495.png">
<img width="1086" alt="screen shot 2018-02-24 at 11 40 37 am" src="https://user-images.githubusercontent.com/11214/36633280-26de96e0-1958-11e8-95ff-494725e87519.png">

<img width="1404" alt="screen shot 2018-02-24 at 11 41 21 am" src="https://user-images.githubusercontent.com/11214/36636807-3dfdb87a-1993-11e8-8bc9-c3f41b80c9fc.png">

<img width="642" alt="screen shot 2018-02-24 at 10 55 43 am" src="https://user-images.githubusercontent.com/11214/36636810-4c6ec70a-1993-11e8-9718-cb0741f79dc6.png">
