### ISSUE TITLE
First go checklist

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#82]
- [x] `capacitor update` clean requirement for iOS? (needed to clean in Xcode before build would succeed) @jcesarmobile 
- [x] Make sure `native-bridge.js` gets copied with `capacitor copy` OR with installing the core command 
- [x] Can we use relative paths for `capacitor update` for pod files to `node_modules`, instead of the absolute path? @jcesarmobile 
- [x] Improve the pod deploy script to avoid the nasty github tag. Can we use lerna?
- [x] Cli shouldn't use Capacitor pod from assets
- [x] Note about pod repo update
- [x] Ship android dependency and add update feature to cli

**Comment by mlynch** [comment]
I removed the old temporary hacks for local cocoapods stuff and tested a working app start to finish

**Comment by jcesarmobile** [comment]
> Improve the pod deploy script to avoid the nasty github tag. Can we use lerna?

For the podspec's source we can use a git tag, branch or commit, or use http to a zip, tgz, bz2, txz or tar file. We could create a script that zips the code and uploads it somewhere always with the same name, but then every app that uses Capacitor will download that zip and use a lot of our bandwidth

**Comment by mlynch** [comment]
@jcesarmobile I mean the tag system for git that cocapods uses for versions. You have to push a tag, say 0.0.9, and then tell cocoapods to update trunk. I'd love for lerna to keep each version locked and do publishes for us

**Comment by jcesarmobile** [comment]
What I mean is, it uses tags because we specified a tag in the podspec, we can use a branch, commit or zipped file instead by changing the source param

**Comment by mlynch** [comment]
I see. I think the tags work but they need to be synced with whatever lerna is doing.

**Comment by mlynch** [comment]
#84 merged

**Comment by mlynch** [comment]
#85 merged to add clean

**Comment by mlynch** [comment]
I started setting up bintray for Android, following what I'm seeing with other libraries like realm: https://bintray.com/realm/maven/realm-gradle-plugin/4.3.3

**Comment by mlynch** [comment]
We went live for the first go! It was rocky but we got it done 🤙 🏄
